-- drop trigger trg_person_insert_audit on person;
-- drop function fnc_trg_person_insert_audit();
--
-- drop trigger trg_person_update_audit on person;
-- drop function fnc_trg_person_update_audit();
--
-- drop trigger trg_person_delete_audit on person;
-- drop function fnc_trg_person_delete_audit();
--
-- truncate table person_audit;
--
-- create function fnc_trg_person_audit()
-- returns trigger as
-- $$
-- begin
--     if tg_op = 'DELETE' then
--         insert into person_audit(
--             row_id,
--             name,
--             age,
--             gender,
--             address,
--             type_event
--         )
--         values (
--             OLD.id,
--             OLD.name,
--             OLD.age,
--             OLD.gender,
--             OLD.address,
--             'D'
--         );
--
--         return OLD;
--
--     elsif tg_op = 'UPDATE' then
--         insert into person_audit(
--             row_id,
--             name,
--             age,
--             gender,
--             address,
--             type_event
--         )
--         values (
--             OLD.id,
--             OLD.name,
--             OLD.age,
--             OLD.gender,
--             OLD.address,
--             'U'
--         );
--
--         return NEW;
--
--     elsif tg_op = 'INSERT' then
--         insert into person_audit(
--             row_id,
--             name,
--             age,
--             gender,
--             address
--         )
--         values (
--             NEW.id,
--             NEW.name,
--             NEW.age,
--             NEW.gender,
--             NEW.address
--         );
--
--         return NEW;
--     end if;
--
--     return null;
-- end;
-- $$ language plpgsql;
--
-- create trigger trg_person_audit
-- after insert or update or delete on person
-- for each row
-- execute function fnc_trg_person_audit();
--
-- insert into person (id, name, age, gender, address)
-- values (10, 'Damir', 22, 'male', 'Irkutsk');
--
-- update person
-- set name = 'Bulat'
-- where id = 10;
--
-- update person
-- set name = 'Damir'
-- where id = 10;
--
-- delete from person
-- where id = 10;

SELECT * FROM person_audit
ORDER BY created;
